2017-09-12 15:53:08,118 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"alwaysMatch": {"platformName": "Android"}, "firstMatch": [{}]}, "desiredCapabilities": {"deviceName": "OPPO R7", "unicodeKeyboard": true, "app": "H:\\project\\Nidone_appium\\app-client-debug-test-2.3.13.apk", "resetKeyboard": true, "platformVersion": "4.4.4", "platformName": "Android"}}
2017-09-12 15:53:27,714 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:53:27,714 - log.py[line:69] - INFO:   run 登录测试.
2017-09-12 15:53:42,726 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/533c68f9-2e13-4d16-8f2f-11bf14b5d4e3/context {"sessionId": "533c68f9-2e13-4d16-8f2f-11bf14b5d4e3", "name": "WEBVIEW"}
2017-09-12 15:53:42,851 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:53:42,851 - Test_Case.py[line:46] - ERROR: Message: No such context found.

2017-09-12 15:53:42,851 - mkdir_log_directory.py[line:29] - INFO: H:\project\Nidone_appium\log\2017-09-12_15_53_07_error目录创建成功
2017-09-12 15:53:44,648 - log.py[line:48] - INFO: 错误截图已保存在 H:\project\Nidone_appium\log\2017-09-12_15_53_07_error
2017-09-12 15:53:44,648 - log.py[line:63] - INFO: 记录错误日志
2017-09-12 15:53:44,648 - log.py[line:71] - INFO:   登录测试 end.
2017-09-12 15:53:44,648 - remote_connection.py[line:478] - DEBUG: DELETE http://127.0.0.1:4723/wd/hub/session/533c68f9-2e13-4d16-8f2f-11bf14b5d4e3 {"sessionId": "533c68f9-2e13-4d16-8f2f-11bf14b5d4e3"}
2017-09-12 15:53:46,466 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:53:47,466 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"alwaysMatch": {"platformName": "Android"}, "firstMatch": [{}]}, "desiredCapabilities": {"deviceName": "OPPO R7", "unicodeKeyboard": true, "app": "H:\\project\\Nidone_appium\\app-client-debug-test-2.3.13.apk", "resetKeyboard": true, "platformVersion": "4.4.4", "platformName": "Android"}}
2017-09-12 15:54:01,938 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:54:01,938 - log.py[line:69] - INFO:   run 登录测试1.
2017-09-12 15:54:16,950 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/a36a6a14-8956-4112-8b2d-dd2d26e1724a/context {"sessionId": "a36a6a14-8956-4112-8b2d-dd2d26e1724a", "name": "WEBVIEW"}
2017-09-12 15:54:17,105 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:54:17,105 - Test_Case.py[line:65] - ERROR: Message: No such context found.

2017-09-12 15:54:18,871 - log.py[line:48] - INFO: 错误截图已保存在 H:\project\Nidone_appium\log\2017-09-12_15_53_07_error
2017-09-12 15:54:18,888 - log.py[line:63] - INFO: 记录错误日志
2017-09-12 15:54:18,888 - log.py[line:71] - INFO:   登录测试1 end.
2017-09-12 15:54:18,888 - remote_connection.py[line:478] - DEBUG: DELETE http://127.0.0.1:4723/wd/hub/session/a36a6a14-8956-4112-8b2d-dd2d26e1724a {"sessionId": "a36a6a14-8956-4112-8b2d-dd2d26e1724a"}
2017-09-12 15:54:20,716 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:54:21,716 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"alwaysMatch": {"platformName": "Android"}, "firstMatch": [{}]}, "desiredCapabilities": {"deviceName": "OPPO R7", "unicodeKeyboard": true, "app": "H:\\project\\Nidone_appium\\app-client-debug-test-2.3.13.apk", "resetKeyboard": true, "platformVersion": "4.4.4", "platformName": "Android"}}
2017-09-12 15:54:36,145 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:54:36,145 - log.py[line:69] - INFO:   run 登录测试3.
2017-09-12 15:54:51,157 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/7874f1ea-f069-4585-b431-6e257f85821f/context {"sessionId": "7874f1ea-f069-4585-b431-6e257f85821f", "name": "WEBVIEW"}
2017-09-12 15:54:51,266 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-12 15:54:51,266 - Test_Case.py[line:84] - ERROR: Message: No such context found.

2017-09-12 15:54:52,970 - log.py[line:48] - INFO: 错误截图已保存在 H:\project\Nidone_appium\log\2017-09-12_15_53_07_error
2017-09-12 15:54:52,970 - log.py[line:63] - INFO: 记录错误日志
2017-09-12 15:54:52,970 - log.py[line:71] - INFO:   登录测试3 end.
2017-09-12 15:54:52,970 - remote_connection.py[line:478] - DEBUG: DELETE http://127.0.0.1:4723/wd/hub/session/7874f1ea-f069-4585-b431-6e257f85821f {"sessionId": "7874f1ea-f069-4585-b431-6e257f85821f"}
2017-09-12 15:54:54,799 - remote_connection.py[line:565] - DEBUG: Finished Request
