<?xml version="1.0" encoding="UTF-8"?>
2017-09-29 23:21:35,938 - log.py[line:88] - INFO:   run 正确登录.
2017-09-29 23:21:35,940 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/194d585b-23f8-4700-89fd-9b5e4b9d8135/context {"sessionId": "194d585b-23f8-4700-89fd-9b5e4b9d8135", "name": "WEBVIEW"}
2017-09-29 23:21:36,102 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-29 23:21:36,104 - creat_case.py[line:116] - ERROR: Message: No such context found.

2017-09-29 23:21:36,105 - mkdir_log_directory.py[line:30] - INFO: D:\project\Nidone_python\Test_Report\2017-09-29_23_20_51_error目录创建成功
2017-09-29 23:21:36,107 - remote_connection.py[line:478] - DEBUG: GET http://127.0.0.1:4723/wd/hub/session/194d585b-23f8-4700-89fd-9b5e4b9d8135/screenshot {"sessionId": "194d585b-23f8-4700-89fd-9b5e4b9d8135"}
